# Generated by Django 3.2.6 on 2021-10-29 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageOffProducts',
        ),
    ]
