# Generated by Django 3.2.6 on 2021-11-03 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_old_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='old_price',
        ),
    ]
