# Generated by Django 3.2.6 on 2021-11-10 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0019_alter_tienda_description'),
        ('products', '0012_alter_images_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='tienda',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='tiendas.tienda', verbose_name='tienda'),
            preserve_default=False,
        ),
    ]
