# Generated by Django 3.2.6 on 2021-11-10 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_images_tienda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='tienda',
        ),
    ]
