# Generated by Django 3.2.6 on 2021-12-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_images_tienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='variaciones',
            name='no_stock',
            field=models.BooleanField(default=False),
        ),
    ]
