# Generated by Django 3.2.6 on 2021-12-24 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_variaciones_no_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variaciones',
            name='no_stock',
        ),
    ]
