# Generated by Django 3.2.6 on 2021-12-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_remove_product_only_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='variaciones',
            name='no_stock',
            field=models.BooleanField(default=False, verbose_name='no_stock'),
        ),
    ]
