# Generated by Django 3.2.6 on 2021-12-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_variaciones_no_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='only_attribute',
            field=models.BooleanField(default=False, verbose_name='only_attribute'),
        ),
    ]
