# Generated by Django 3.2.6 on 2021-12-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_product_only_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='atributos',
            name='repeat',
            field=models.IntegerField(default=0, verbose_name='Repetir'),
        ),
    ]
