# Generated by Django 3.2.6 on 2022-01-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_atributos_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_options',
            field=models.BooleanField(default=False, verbose_name='Con_opciones'),
        ),
    ]
