# Generated by Django 3.2.6 on 2022-01-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_remove_product_has_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='only_attribute',
            field=models.BooleanField(default=True, verbose_name='only_attribute'),
        ),
    ]
