# Generated by Django 3.2.6 on 2022-01-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_product_has_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='no_stock',
            field=models.BooleanField(default=False, verbose_name='no_stock'),
        ),
    ]
