# Generated by Django 3.2.6 on 2022-05-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0030_preguntaproduct_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntaproduct',
            old_name='text',
            new_name='pregunta',
        ),
        migrations.RemoveField(
            model_name='preguntaproduct',
            name='response',
        ),
        migrations.AddField(
            model_name='preguntaproduct',
            name='respuesta',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
