# Generated by Django 3.2.6 on 2022-05-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_auto_20220524_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntaproduct',
            name='visto',
            field=models.BooleanField(default=False, verbose_name='visto'),
        ),
    ]
