# Generated by Django 3.2.6 on 2021-10-22 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='personal_user_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userpersonaldata', verbose_name='Datos Personales'),
        ),
    ]
