# Generated by Django 3.2.6 on 2021-11-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_personal_user_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='visto',
            field=models.BooleanField(default=False, verbose_name='viste'),
        ),
    ]
