# Generated by Django 3.2.6 on 2021-11-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_visto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='visto',
            field=models.BooleanField(default=False, verbose_name='visto'),
        ),
    ]
