# Generated by Django 3.2.6 on 2021-12-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_visto'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='collection_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='collection_id'),
        ),
        migrations.AddField(
            model_name='order',
            name='collection_status',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='collection_status'),
        ),
        migrations.AddField(
            model_name='order',
            name='merchant_order_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='merchant_order_id'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='payment_id'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='payment_type'),
        ),
    ]
