# Generated by Django 3.2.6 on 2021-12-01 20:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_external_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='collection_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='collection_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='external_reference',
        ),
        migrations.RemoveField(
            model_name='order',
            name='merchant_order_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_type',
        ),
        migrations.CreateModel(
            name='OrderMercadoPagoDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('collection_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='collection_id')),
                ('collection_status', models.CharField(blank=True, max_length=10, null=True, verbose_name='collection_status')),
                ('payment_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='payment_id')),
                ('payment_type', models.CharField(blank=True, max_length=20, null=True, verbose_name='payment_type')),
                ('merchant_order_id', models.CharField(blank=True, max_length=20, null=True, verbose_name='merchant_order_id')),
                ('external_reference', models.CharField(blank=True, max_length=15, null=True, verbose_name='external_reference')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Orden')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
