# Generated by Django 3.2.6 on 2021-12-01 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20211201_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermercadopagodetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_mp_detail', to='orders.order', verbose_name='Orden'),
        ),
    ]
