# Generated by Django 3.2.6 on 2021-12-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_ordermercadopagodetail_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='metodo_pago_status',
            field=models.BooleanField(blank=True, null=True, verbose_name='metodo_pago_status'),
        ),
    ]
