# Generated by Django 3.2.6 on 2021-12-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_metodo_pago_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='metodo_pago_status',
            field=models.BooleanField(default=False, verbose_name='metodo_pago_status'),
        ),
    ]
