# Generated by Django 3.2.6 on 2021-12-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_metodo_pago_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='metodo_pago_status',
        ),
        migrations.AddField(
            model_name='order',
            name='mercado_pago_status',
            field=models.BooleanField(default=False, verbose_name='mercado_pago_status'),
        ),
    ]
