# Generated by Django 3.2.6 on 2021-12-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20211201_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='mercado_pago_status',
        ),
        migrations.AddField(
            model_name='order',
            name='mercado_pago_approved',
            field=models.BooleanField(default=False, verbose_name='mercado_pago_approved'),
        ),
    ]
