# Generated by Django 3.2.6 on 2021-12-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20211201_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mercado_pago_approved',
            field=models.BooleanField(verbose_name='mercado_pago_approved'),
        ),
    ]
