# Generated by Django 3.2.6 on 2021-12-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_mercado_pago_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermercadopagodetail',
            name='collection_id',
            field=models.CharField(max_length=20, verbose_name='collection_id'),
        ),
        migrations.AlterField(
            model_name='ordermercadopagodetail',
            name='collection_status',
            field=models.CharField(max_length=10, verbose_name='collection_status'),
        ),
        migrations.AlterField(
            model_name='ordermercadopagodetail',
            name='external_reference',
            field=models.CharField(max_length=15, verbose_name='external_reference'),
        ),
        migrations.AlterField(
            model_name='ordermercadopagodetail',
            name='merchant_order_id',
            field=models.CharField(max_length=20, verbose_name='merchant_order_id'),
        ),
        migrations.AlterField(
            model_name='ordermercadopagodetail',
            name='payment_id',
            field=models.CharField(max_length=20, verbose_name='payment_id'),
        ),
        migrations.AlterField(
            model_name='ordermercadopagodetail',
            name='payment_type',
            field=models.CharField(max_length=20, verbose_name='payment_type'),
        ),
    ]
