# Generated by Django 3.2.6 on 2021-12-02 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20211201_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermercadopagodetail',
            options={'verbose_name': 'MercadoPago Detalle', 'verbose_name_plural': 'MercadoPago Detalles'},
        ),
        migrations.AlterField(
            model_name='order',
            name='mercado_pago_approved',
            field=models.BooleanField(default=False, verbose_name='mercado_pago_approved'),
        ),
        migrations.AlterField(
            model_name='ordermercadopagodetail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_mp_detail', to='orders.order', verbose_name='Orden_'),
        ),
    ]
