# Generated by Django 3.2.6 on 2021-12-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20211202_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='estado',
            field=models.CharField(default='en espera', max_length=20, verbose_name='estado'),
        ),
    ]
