# Generated by Django 3.2.6 on 2021-12-09 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_order_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pago',
            field=models.CharField(default='pendiente', max_length=11, verbose_name='pago'),
        ),
    ]
