# Generated by Django 3.2.6 on 2021-12-10 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0028_auto_20211207_0102'),
        ('orders', '0017_order_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiendas.envios', verbose_name='Envio'),
        ),
    ]
