# Generated by Django 3.2.6 on 2021-12-10 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_order_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='precio_envio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='precio_envio'),
        ),
    ]
