# Generated by Django 3.2.6 on 2021-12-10 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_precio_envio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='precio_envio',
        ),
    ]
