# Generated by Django 3.2.6 on 2021-12-11 17:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('orders', '0020_remove_order_precio_envio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousPersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='apellido')),
                ('email', models.CharField(max_length=100, verbose_name='email')),
                ('pais', models.CharField(max_length=50, verbose_name='pais')),
                ('ciudad', models.CharField(max_length=50, verbose_name='ciudad')),
                ('estado', models.CharField(max_length=50, verbose_name='estado/provincia')),
                ('direccion', models.CharField(max_length=80, verbose_name='direccion')),
                ('apartamento', models.CharField(blank=True, max_length=10, null=True, verbose_name='apartamento')),
                ('codigo_postal', models.CharField(max_length=50, verbose_name='codigo postal')),
                ('telefono', models.CharField(max_length=50, verbose_name='telefono')),
            ],
            options={
                'verbose_name': 'Datos personales',
                'verbose_name_plural': 'Datos personales',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='personal_user_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userpersonaldata', verbose_name='Datos Personales'),
        ),
        migrations.AddField(
            model_name='order',
            name='anonymous_user_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.anonymouspersonaldata', verbose_name='anonymous_user_data'),
        ),
    ]
