# Generated by Django 3.2.6 on 2021-12-11 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0021_auto_20211211_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anonymouspersonaldata',
            options={'verbose_name': 'anonymous user data', 'verbose_name_plural': 'anonymous user data'},
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
