# Generated by Django 3.2.6 on 2022-04-06 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0044_remove_plan_bookings'),
        ('orders', '0024_order_detail_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendas.tienda', verbose_name='Tienda'),
        ),
    ]
