# Generated by Django 3.2.6 on 2022-12-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_alter_order_tienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymouspersonaldata',
            name='dni',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='telefono'),
        ),
    ]
