# Generated by Django 3.2.6 on 2022-12-07 17:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userpersonaldata_dni'),
        ('products', '0036_product_visits'),
        ('orders', '0026_anonymouspersonaldata_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('token', models.CharField(max_length=16, verbose_name='token')),
                ('anonymous_user_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.anonymouspersonaldata', verbose_name='anonymous_user_data')),
                ('personal_user_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userpersonaldata', verbose_name='Datos Personales')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_evento', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
