# Generated by Django 3.2.6 on 2022-12-07 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
    ]
