# Generated by Django 3.2.6 on 2022-01-12 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0004_auto_20220112_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousPersonalServiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=50, null=True, verbose_name='apellido')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='telefono')),
            ],
            options={
                'verbose_name': 'anonymous user service data',
                'verbose_name_plural': 'anonymous user service data',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='anonymous_personal_service_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='services.anonymouspersonalservicedata', verbose_name='anonymous_user_data'),
        ),
    ]
