# Generated by Django 3.2.6 on 2022-01-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20220120_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='visto',
            field=models.BooleanField(default=False, verbose_name='visto'),
        ),
    ]
