# Generated by Django 3.2.6 on 2022-02-01 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211227_1829'),
        ('services', '0013_booking_visto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='user_personal_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userpersonaldata'),
        ),
        migrations.AlterField(
            model_name='anonymouspersonalservicedata',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='apellido'),
        ),
        migrations.AlterField(
            model_name='anonymouspersonalservicedata',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='anonymouspersonalservicedata',
            name='telefono',
            field=models.CharField(max_length=50, verbose_name='telefono'),
        ),
    ]
