# Generated by Django 3.2.6 on 2022-04-19 16:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0049_alter_tienda_extra_field'),
        ('services', '0014_auto_20220201_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category', verbose_name='Imagen')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='services.category_service')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendas.tienda', verbose_name='tienda_service_category')),
            ],
            options={
                'verbose_name': 'Categoria de servicio',
                'verbose_name_plural': 'Categorias servicios',
            },
        ),
    ]
