# Generated by Django 3.2.6 on 2022-04-20 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0051_plan_images_x_services'),
        ('services', '0017_service_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_images',
            name='tienda',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='tiendas.tienda', verbose_name='tienda_service'),
            preserve_default=False,
        ),
    ]
