# Generated by Django 3.2.6 on 2022-05-23 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_opinionesservices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opinionesservices',
            options={'verbose_name': 'Opinion Servicio', 'verbose_name_plural': 'Opiniones Servicios'},
        ),
    ]
