# Generated by Django 3.2.6 on 2022-05-26 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_preguntaservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preguntaservice',
            old_name='product',
            new_name='service',
        ),
    ]
