# Generated by Django 3.2.6 on 2022-08-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_rename_product_preguntaservice_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='completed'),
        ),
        migrations.AddField(
            model_name='service',
            name='only_show',
            field=models.BooleanField(default=False, verbose_name='only_show'),
        ),
        migrations.AlterField(
            model_name='category_service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_service', verbose_name='Imagen'),
        ),
    ]
