# Generated by Django 3.2.6 on 2022-09-06 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_alter_service_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='completed',
        ),
    ]
