# Generated by Django 3.2.6 on 2022-09-06 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_remove_service_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='completed'),
        ),
    ]
