# Generated by Django 3.2.6 on 2022-09-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0029_booking_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='payment',
            field=models.BooleanField(default=False, verbose_name='payment'),
        ),
        migrations.AddField(
            model_name='service',
            name='payment_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='payment_price'),
        ),
    ]
