# Generated by Django 3.2.6 on 2022-09-13 04:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_auto_20220906_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingMercadoPagoDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('collection_id', models.CharField(max_length=20, verbose_name='collection_id')),
                ('collection_status', models.CharField(max_length=10, verbose_name='collection_status')),
                ('payment_id', models.CharField(max_length=20, verbose_name='payment_id')),
                ('payment_type', models.CharField(max_length=20, verbose_name='payment_type')),
                ('merchant_order_id', models.CharField(max_length=20, verbose_name='merchant_order_id')),
                ('external_reference', models.CharField(max_length=15, verbose_name='external_reference')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_mp_detail', to='services.booking', verbose_name='booking')),
            ],
            options={
                'verbose_name': 'Booking MercadoPago Detalle',
                'verbose_name_plural': 'Bookings MercadoPago Detalles',
            },
        ),
    ]
