# Generated by Django 3.2.6 on 2021-10-19 05:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tiendas', '0003_auto_20211019_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('short_name', models.CharField(max_length=20, unique=True, verbose_name='Nombre Corto')),
                ('name', models.CharField(max_length=30, verbose_name='Nombres')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendas.tienda', verbose_name='tienda_blog_category')),
            ],
            options={
                'verbose_name': 'Categoria Blog',
                'verbose_name_plural': 'Categorias Blog',
            },
        ),
        migrations.CreateModel(
            name='ImagesOffEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image', models.ImageField(upload_to='entry_images', verbose_name='Imagenes')),
            ],
            options={
                'verbose_name': 'Imagen de la entrada',
                'verbose_name_plural': 'Imagenes de las entradas',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Etiqueta Blog',
                'verbose_name_plural': 'Etiquetas Blog',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=200, verbose_name='Titulo')),
                ('resume', models.TextField(verbose_name='Resumen')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('public', models.BooleanField(default=False, verbose_name='publico')),
                ('image', models.ImageField(upload_to='entry', verbose_name='Imagen')),
                ('portada', models.BooleanField(default=False, verbose_name='Portada')),
                ('in_home', models.BooleanField(default=False, verbose_name='En Home')),
                ('slug', models.SlugField(editable=False, max_length=300, verbose_name='Slug')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category_blog', verbose_name='categoria_blog')),
                ('images', models.ManyToManyField(blank=True, to='blog.ImagesOffEntries')),
                ('tag', models.ManyToManyField(to='blog.Tag', verbose_name='tag')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendas.tienda', verbose_name='tienda_blog_entry')),
            ],
            options={
                'verbose_name': 'Entrada',
                'verbose_name_plural': 'Entradas',
            },
        ),
    ]
