# Generated by Django 3.2.6 on 2021-10-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category_blog',
            name='short_name',
            field=models.CharField(max_length=20, verbose_name='Nombre Corto'),
        ),
    ]
