# Generated by Django 3.2.6 on 2021-10-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_category_blog_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='in_home',
        ),
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, null=True, verbose_name='Slug'),
        ),
    ]
