# Generated by Django 3.2.6 on 2021-10-28 15:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211028_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='images',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='resume',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image', models.ImageField(upload_to='entry_images', verbose_name='Imagenes')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_entry', to='blog.entry', verbose_name='entrada')),
            ],
            options={
                'verbose_name': 'Imagen de la entrada',
                'verbose_name_plural': 'Imagenes de las entradas',
            },
        ),
    ]
