# Generated by Django 3.2.6 on 2021-10-28 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211028_1232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagesOffEntries',
        ),
    ]
