# Generated by Django 3.2.6 on 2021-10-28 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_delete_imagesoffentries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Tag', verbose_name='tag'),
        ),
    ]
