# Generated by Django 3.2.6 on 2021-10-28 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_entry_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='tag',
        ),
    ]
