# Generated by Django 3.2.6 on 2021-10-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_entry_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='entry_images', verbose_name='Imagen'),
        ),
    ]
