# Generated by Django 3.2.6 on 2021-11-12 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0019_alter_tienda_description'),
        ('blog', '0009_alter_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='tienda',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='images_entry_tienda', to='tiendas.tienda', verbose_name='tienda'),
            preserve_default=False,
        ),
    ]
