# Generated by Django 3.2.6 on 2022-06-23 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_images_tienda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('text', models.CharField(max_length=255, verbose_name='comentario')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.entry', verbose_name='entrada')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.comment_entry')),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_user_entry_commnet', to=settings.AUTH_USER_MODEL, verbose_name='usuario_response')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_entry_comment', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Comentario entrada',
                'verbose_name_plural': 'Comentarios entradas',
            },
        ),
    ]
