# Generated by Django 3.2.6 on 2022-06-23 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_comment_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_entry',
            name='parent_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_user_entry_commnet', to=settings.AUTH_USER_MODEL, verbose_name='usuario_response'),
        ),
    ]
