# Generated by Django 3.2.6 on 2022-05-07 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_visitor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'verbose_name': 'Visitante', 'verbose_name_plural': 'Visitantes'},
        ),
    ]
