# Generated by Django 3.2.6 on 2021-10-19 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0002_auto_20211019_0207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'Plan', 'verbose_name_plural': 'Planes'},
        ),
        migrations.AlterField(
            model_name='tienda',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendas.plan', verbose_name='Plan'),
        ),
    ]
