# Generated by Django 3.2.6 on 2021-10-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0005_auto_20211023_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='alerts_font',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='alerts_fonts'),
        ),
        migrations.AlterField(
            model_name='colors',
            name='bottom_navigation_font',
            field=models.BooleanField(blank=True, null=True, verbose_name='bottom_navigation_font'),
        ),
    ]
