# Generated by Django 3.2.6 on 2021-10-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0006_auto_20211024_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='bottom_navigation_font',
            field=models.BooleanField(default=True, verbose_name='bottom_navigation_font'),
        ),
    ]
