# Generated by Django 3.2.6 on 2021-10-25 06:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0007_alter_colors_bottom_navigation_font'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('image', models.ImageField(upload_to='slider', verbose_name='Imagen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='colors',
            name='background_color',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='background_color'),
        ),
        migrations.AlterField(
            model_name='colors',
            name='navbar_font',
            field=models.CharField(blank=True, default='#ffffff', max_length=15, null=True, verbose_name='navbar_font'),
        ),
        migrations.AddField(
            model_name='colors',
            name='texture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiendas.textures', verbose_name='fondo_textura'),
        ),
    ]
