# Generated by Django 3.2.6 on 2021-10-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0008_auto_20211025_0317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textures',
            options={'verbose_name': 'Textura', 'verbose_name_plural': 'Texturas'},
        ),
        migrations.AlterField(
            model_name='colors',
            name='background_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=15, null=True, verbose_name='background_color'),
        ),
        migrations.AlterField(
            model_name='textures',
            name='image',
            field=models.ImageField(upload_to='Textures', verbose_name='Imagen'),
        ),
    ]
