# Generated by Django 3.2.6 on 2021-10-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0009_auto_20211025_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='colors',
            name='hasTexture',
            field=models.BooleanField(default=False, verbose_name='hasTexture'),
        ),
    ]
