# Generated by Django 3.2.6 on 2021-10-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0013_alter_tienda_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='titulo'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='logo',
            field=models.ImageField(blank=True, default='/defaults/bag1.png', null=True, upload_to='logo', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='tienda',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='dominio'),
        ),
    ]
