# Generated by Django 3.2.6 on 2021-10-26 17:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0014_auto_20211026_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('dias_habiles', models.CharField(blank=True, max_length=100, null=True, verbose_name='dias_habiles')),
                ('horario', models.CharField(blank=True, max_length=100, null=True, verbose_name='horario')),
                ('envio', models.CharField(blank=True, max_length=100, null=True, verbose_name='envio')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='direccion')),
                ('telefono', models.CharField(blank=True, max_length=100, null=True, verbose_name='telefono')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendas.tienda', verbose_name='tienda')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
