# Generated by Django 3.2.6 on 2021-10-26 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0015_informacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informacion',
            options={'verbose_name': 'Informacion', 'verbose_name_plural': 'Informacion'},
        ),
        migrations.AddField(
            model_name='colors',
            name='info_background_color',
            field=models.CharField(blank=True, default='#FFFFFF', max_length=15, null=True, verbose_name='info_background_color'),
        ),
        migrations.AddField(
            model_name='colors',
            name='info_font_color',
            field=models.CharField(blank=True, default='#000000', max_length=15, null=True, verbose_name='info_font_color'),
        ),
        migrations.AddField(
            model_name='colors',
            name='info_icons_color',
            field=models.CharField(blank=True, default='#607d8b', max_length=15, null=True, verbose_name='info_icons_color'),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='dias_habiles',
            field=models.CharField(blank=True, default='Lunes a Viernes', max_length=100, null=True, verbose_name='dias_habiles'),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='direccion',
            field=models.CharField(blank=True, default='San Martin 3250,Rosario,Santa Fe,Argentina', max_length=100, null=True, verbose_name='direccion'),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='envio',
            field=models.CharField(blank=True, default='envios a todo el pais', max_length=100, null=True, verbose_name='envio'),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='horario',
            field=models.CharField(blank=True, default='De 09:00 a 13:00 y 15:00 a 19:00', max_length=100, null=True, verbose_name='horario'),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='telefono',
            field=models.CharField(blank=True, default='54 9 3415 666777', max_length=100, null=True, verbose_name='telefono'),
        ),
        migrations.AlterField(
            model_name='informacion',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tienda_informacion', to='tiendas.tienda', verbose_name='tienda'),
        ),
    ]
