# Generated by Django 3.2.6 on 2021-12-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0024_mercadopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='informacion',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='whatsapp'),
        ),
    ]
