# Generated by Django 3.2.6 on 2021-12-02 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0026_auto_20211202_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion',
            name='dias_horarios',
            field=models.TextField(blank=True, default='Lunes a Viernes De 09:00 a 13:00 y 15:00 a 19:00, Sabado de 09:00 a 13:00', null=True, verbose_name='horario'),
        ),
    ]
