# Generated by Django 3.2.6 on 2021-12-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0029_alter_tienda_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='tipo_tienda',
            field=models.IntegerField(default=1, verbose_name='tipo_tienda'),
        ),
    ]
