# Generated by Django 3.2.6 on 2021-12-28 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0031_favoritos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritos',
            options={'verbose_name': 'Favorito', 'verbose_name_plural': 'Favoritos'},
        ),
    ]
