# Generated by Django 3.2.6 on 2022-02-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0032_alter_favoritos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='images_sliders',
            field=models.IntegerField(default=1, verbose_name='imagenes_x_entrada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='services',
            field=models.IntegerField(default=1, verbose_name='imagenes_x_entrada'),
            preserve_default=False,
        ),
    ]
