# Generated by Django 3.2.6 on 2022-03-02 18:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0033_auto_20220208_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='images_sliders',
            field=models.IntegerField(verbose_name='imagenes_sliders'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='services',
            field=models.IntegerField(verbose_name='servicios'),
        ),
        migrations.CreateModel(
            name='Codigoqr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendas.tienda', verbose_name='tienda')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
