# Generated by Django 3.2.6 on 2022-03-17 22:07

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0035_auto_20220315_1830'),
    ]

    operations = [
    ]
