# Generated by Django 3.2.6 on 2022-03-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0038_auto_20220319_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripcion'),
        ),
    ]
