# Generated by Django 3.2.6 on 2022-03-25 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0039_alter_tienda_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Geolocalization',
        ),
    ]
