# Generated by Django 3.2.6 on 2022-03-25 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0040_delete_geolocalization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geolocalization_geodjango',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goe_tienda', to='tiendas.tienda', verbose_name='tienda'),
        ),
    ]
