# Generated by Django 3.2.6 on 2022-04-05 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0043_auto_20220401_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='bookings',
        ),
    ]
