# Generated by Django 3.2.6 on 2022-04-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0044_remove_plan_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='bookings',
            field=models.IntegerField(default=30, verbose_name='reservas'),
            preserve_default=False,
        ),
    ]
