# Generated by Django 3.2.6 on 2022-04-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0045_plan_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='description',
            field=models.CharField(default=0, max_length=255, verbose_name='Descripcion'),
            preserve_default=False,
        ),
    ]
