# Generated by Django 3.2.6 on 2022-04-08 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0046_alter_tienda_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacion',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='informacion',
            name='envio',
        ),
    ]
