# Generated by Django 3.2.6 on 2022-04-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0048_auto_20220412_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='extra_field',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='extra_field'),
        ),
    ]
