# Generated by Django 3.2.6 on 2022-04-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0049_alter_tienda_extra_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='services_categories',
            field=models.IntegerField(default=4, verbose_name='servicios_categorias'),
            preserve_default=False,
        ),
    ]
