# Generated by Django 3.2.6 on 2022-04-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0050_plan_services_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='images_x_services',
            field=models.IntegerField(default=4, verbose_name='imagenes_x_servicio'),
            preserve_default=False,
        ),
    ]
