# Generated by Django 3.2.6 on 2022-04-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0051_plan_images_x_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='title',
            field=models.CharField(default='mitienda', max_length=30, verbose_name='titulo'),
            preserve_default=False,
        ),
    ]
