# Generated by Django 3.2.6 on 2022-05-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0054_opiniones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opiniones',
            name='opinion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
