# Generated by Django 3.2.6 on 2022-05-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0055_alter_opiniones_opinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opiniones',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, verbose_name='Rating'),
        ),
    ]
