# Generated by Django 3.2.6 on 2022-06-27 15:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0056_alter_opiniones_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('domain', models.CharField(max_length=30, verbose_name='dominio')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tiendas.tienda', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Opinion',
                'verbose_name_plural': 'Opiniones',
            },
        ),
    ]
