# Generated by Django 3.2.6 on 2022-06-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0057_modelfake'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelFake',
        ),
    ]
