# Generated by Django 3.2.6 on 2022-06-28 01:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0058_delete_modelfake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='hasTexture',
            field=models.BooleanField(default=True, verbose_name='hasTexture'),
        ),
        migrations.AlterField(
            model_name='colors',
            name='info_background_color',
            field=models.CharField(blank=True, default='#9c06a8', max_length=15, null=True, verbose_name='info_background_color'),
        ),
        migrations.AlterField(
            model_name='colors',
            name='texture',
            field=models.ForeignKey(blank=True, default=15, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tiendas.textures', verbose_name='fondo_textura'),
        ),
        migrations.CreateModel(
            name='Title_font',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=20, verbose_name='nombre')),
                ('url', models.CharField(max_length=200, verbose_name='url')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tienda_title_font', to='tiendas.tienda', verbose_name='tienda')),
            ],
            options={
                'verbose_name': 'fuente_titulo',
                'verbose_name_plural': 'fuents titulo',
            },
        ),
    ]
