# Generated by Django 3.2.6 on 2022-06-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0061_title_font_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title_font',
            name='css',
            field=models.CharField(max_length=100, verbose_name='css'),
        ),
    ]
