# Generated by Django 3.2.6 on 2022-06-30 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0062_alter_title_font_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title_font',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='nombre'),
        ),
    ]
