# Generated by Django 3.2.6 on 2022-06-30 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0063_alter_title_font_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='font_title',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='tiendas.title_font', verbose_name='fuente_titulo'),
        ),
    ]
