# Generated by Django 3.2.6 on 2022-06-30 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0064_alter_colors_font_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='colors',
            name='font_title_size',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(40)], verbose_name='Tamaño de la fuente'),
        ),
    ]
