# Generated by Django 3.2.6 on 2022-07-08 07:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0065_colors_font_title_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigoqr',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='tiendas.tienda', verbose_name='tienda'),
        ),
        migrations.AlterField(
            model_name='colors',
            name='font_title_size',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(60)], verbose_name='Tamaño de la fuente'),
        ),
    ]
