# Generated by Django 3.2.6 on 2022-10-20 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0067_paymentmethods'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethods',
            options={'verbose_name': 'Metodo de pago', 'verbose_name_plural': 'Metodos de pago'},
        ),
    ]
