# Generated by Django 3.2.6 on 2022-10-27 05:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0068_alter_paymentmethods_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethods',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='tiendas.tienda', verbose_name='tienda'),
        ),
        migrations.CreateModel(
            name='TransferData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('bank', models.CharField(max_length=50, verbose_name='banco')),
                ('alias', models.CharField(blank=True, max_length=100, null=True, verbose_name='alias')),
                ('cbu', models.CharField(max_length=100, verbose_name='cbu')),
                ('tienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_data', to='tiendas.tienda', verbose_name='tienda')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
