# Generated by Django 3.2.6 on 2022-10-27 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendas', '0069_auto_20221027_0205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferdata',
            options={'verbose_name': 'Data de transferencia', 'verbose_name_plural': 'Data de transferencia'},
        ),
    ]
